### PR TITLE
Major overhauls - csu-scheduler implimentation

### PR DESCRIPTION
**Pull request by Shizcow**
In April this year, stevens-scheduler was cloned and completely overhauled for Colorado State University. Many new features, fixes, and improvements were made to bring this project to the next level. See a live demo [here](https://shizcow.github.io/csu-scheduler/).

Now, all those new features have been brought to sitscheduler with a few additional bug fixes.

Google analytics and heeduser have been maintained, no edits needed.

### CODE REVIEW

**Comment by danielheyman** [comment]
Thank you for opening a PR. I will review it within the next couple weeks when I get a chance. I do recommend that you set up a cheap proxy server to get around your cors issue. I host a similar server for stevens. There are many services such as pivotal that will get you the first year for free if you run a small node application.

**Comment by Shizcow** [comment]
Thanks for the recommendation about a proxy server. I'm currently working with my institution on whether or not they'll be nice and host a server for me or what they want me to do otherwise. However, I decided to leave in information about CORS for those looking to adapt this project for other colleges. Luckily, you shouldn't have this problem though.

**Comment by Shizcow** [comment]
After a year of tweaking, I'd consider this fork "very stable", as I've been using the same engine to schedule my classes. Any chances on getting this pull request merged?
I'm also up to becoming a maintainer for this repo if you're interested in giving write access.

**Comment by Shizcow** [comment]
I don't even maintain my own implementation anymore so I no longer care about this

**Pull request closed without merging**
